### PR TITLE
Modal background colour variables

### PR DESCRIPTION
**Pull request by stuartgiles**
#### What does this PR do?
The HEHA theme is "inverted", i.e. light text on a dark background.
Modals do not automatically pull through the body background colour or text colour so we need to set the variables.

1. Background colour set to the same as the body colour (purple), allowing for the white text to be readable.
2. Dark purple borders to define the element boundaries.
3. Padding for a little more spacing.

#### What tests does this PR have?
N/A

#### How can this be tested?
First you'll need to re-compile the .less.

Then create a HEHA! page by making a carpark booking with a flight to Barcelona & go through to holiday manager. Grab the rails-id (the number at the end of the url) & add it to localhost:5000/#heha/your-rails-id.

You can see the results of this PR by viewing the modals "Login" and "Policy".

#### Screenshots / Screencast
I don't have an actual HEHA example to show you, but it should look something like this example.
Ignore the content differences, you're specifically looking for the 3 things mentioned above.

heha-modal

#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by shackpank** [comment]
screen shot 2015-10-28 at 13 31 20

Much better :+1: 

Just noticed the close link though isn't very visible. Did we want to sort that now or can it wait? (I'm happy with things as-is because you can close the modal by clicking anywhere outside it, you don't have to use that link.)

**Comment by Joezo** [comment]
:+1:

**Comment by stuartgiles** [comment]
I have just updated this branch in response to @shackpank's comment about the close button.
* Link colour : Yellow
* Text shadow : None
* Text opacity : 1

**Comment by Joezo** [comment]
Looking good still
screen shot 2015-10-28 at 15 29 21

**Comment by stuartgiles** [comment]
Cool!
I think I'll consider the underline (in fact all link underlines) in a future PR.
Thank you

**Pull request merged**
